# Install cowsay then run the command and append to a file.
# Save as .github/workflows/cowsay.yml
on: [push]

jobs:
  cowsay-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cowsay (Ubuntu)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay

      - name: Run cowsay
        run: |
          # note: fixed filename to "dragon.txt" (you had "gragon.txt" which may be a typo)
          cowsay -f dragon "Run cover, I am a DRAGON.....RAWR" >> dragon.txt
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-output
          path: dragon.txt